/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface YoutubePlayer {
    'id': string;
    'key': string;
    'size': string;
  }
  interface YoutubePlayerAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'key'?: string;
    'size'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'YoutubePlayer': Components.YoutubePlayer;
  }

  interface StencilIntrinsicElements {
    'youtube-player': Components.YoutubePlayerAttributes;
  }


  interface HTMLYoutubePlayerElement extends Components.YoutubePlayer, HTMLStencilElement {}
  var HTMLYoutubePlayerElement: {
    prototype: HTMLYoutubePlayerElement;
    new (): HTMLYoutubePlayerElement;
  };

  interface HTMLElementTagNameMap {
    'youtube-player': HTMLYoutubePlayerElement
  }

  interface ElementTagNameMap {
    'youtube-player': HTMLYoutubePlayerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
